### PR TITLE
Remove `list_batch_recent_inbound/outbound_keys`

### PR DESCRIPTION
**Pull request by JayH5**
Since the regular `list_batch` methods now return results in descending timestamp order, these methods are effectively redundant.

### CODE REVIEW

**Comment by JayH5** [comment]
Ready for review.

One concern: now the only use for `list_batch_inbound_keys`, `list_batch_outbound_keys`, and `list_batch_event_keys` in `batch_info_cache` is for testing `message_store` :confused:

**Comment by jerith** [comment]
I don't think that's really a problem, although it might make sense to write the tests differently now.

**Comment by JayH5** [comment]
OK, well now for the message store tests I'm just doing a count comparison to make sure the messages were added to the cache. Slightly less precise but good enough I think?

**Comment by jerith** [comment]
Excellent, thanks. :+1:

**Pull request merged**
