### PR TITLE
Remove message list variants

### PR DESCRIPTION
**Pull request by JayH5**
We currently have a number of "list message" methods that vary in the content of their responses. Now that they're all using the same index, we should simplify the API by removing the unnecessary variation.

### CODE REVIEW

**Comment by JayH5** [comment]
Ready for review :stuck_out_tongue: 
Two things:
1. Perhaps we should do a release and land praekelt/vumi-go#1310 before this...
2. The `max_results` parameter name is a bit misleading. Why not `page_size`?

**Comment by jerith** [comment]
1. I'd like to make this change before praekelt/vumi-go#1310 lands, because this is part of the public API that vumi-go needs to use.
2. Switching to `page_size` consistently works for me. I mostly used `max_results` because that's what the underlying API calls it.

**Comment by JayH5** [comment]
OK, I thought maybe this change would change #1310 so much that it'd make sense to have 2 PRs...

Another thing, in the actual interface,  the `max_results` parameter is never actually specified but the implementers have it... is/was that intentional?

**Comment by jerith** [comment]
It probably does make sense to expose `page_size` and `continuation_token` in the public API.

**Comment by JayH5** [comment]
I've renamed `max_results` to `page_size` everywhere it makes sense.

Leaving exposing `page_size` and `continuation_token` in the public API for a separate issue.

**Comment by jerith** [comment]
:+1:

**Pull request merged**
